Fix: PlatformIO build
JGMaker3dofficial/artistd pull request #7
Opened 2021-01-28 18:29 UTC by mikejr83

Fix `platformio.ini` for correct build environment.

Closes #6

2021-01-28 18:32 UTC, attacktwinkie commented
What version of Platformio are you basing this on?

2021-01-28 19:50 UTC, attacktwinkie commented on platformio.ini
> +src_filter  = ${common.default_src_filter} +<src/HAL/HAL_ESP32>
Remove the Whitespace changes.

2021-01-28 19:53 UTC, attacktwinkie requested changes
Clean up the whitespace and we'll merge it.

2021-01-28 19:53 UTC, attacktwinkie commented on platformio.ini
> +src_filter  = ${common.default_src_filter} +<src/HAL/HAL_STM32>
These are all whitespace changes that should be removed.

2021-01-28 19:53 UTC, attacktwinkie commented on platformio.ini
> +default_envs = mks_robin_pro
Approved

2021-01-28 19:53 UTC, attacktwinkie commented on platformio.ini
> +lib_ignore    = Adafruit NeoPixel, SPI
This is great, but you need to add one line of whitespace above it.

2021-01-28 19:53 UTC, attacktwinkie commented on platformio.ini
> +lib_ignore    = Adafruit NeoPixel, SPI
NO changes needed, this is pefect.

2021-02-13 03:02 UTC, attacktwinkie commented
This should be fixed now starting with 2021.2 branch.

2021-02-13 16:04 UTC, mikejr83 commented
Closing as obsolete.

2021-02-13 16:04 UTC, closed without merging